image: gitpod/workspace-postgres
ports:
  - port: 3000
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
  - port: 5000
    onOpen: ignore
tasks:
  # both .bashrc and nvm settings get wiped when a workspace is restarted, so
  # they need setting here
  - before: |
      echo 'export IS_DOCKER=""' >> ~/.bashrc &&
      export IS_DOCKER="" &&
      nvm install lts/fermium && nvm alias default lts/fermium
    # the rest, environment variables, installation and db setup, get persisted,
    # so we can save time and use init:
    init: |
      cp .env.example .env &&
      echo NEXT_PUBLIC_APOLLO_SERVER=$(gp url 5000) >> client/.env.development.local &&
      createuser -d postgres &&
      createdb chapter &&
      npx recursive-install &&
      npm run db:reset
    command: npm run both
