# Dev specific configuration
version: "3.7"
services:
  app:
    command: sh -c './wait-for db:5432 -- npm run dev'
    volumes:
      - ./:/usr/chapter/

  client:
    command: npm run dev
    volumes:
      - ./:/usr/chapter/

  mailhog:
    depends_on:
      - app
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"