# This entire service is a hack to let us update the db from inside the droplet
# Reason being: the db only accepts connections from specific IPs and GitHub
# actions are not on the list. They can ssh into the droplet and call this
# service. There must be a better way.
version: "3.7"
services:
  seed:
    env_file: .env
    build:
      context: .
      dockerfile: server.Dockerfile
      target: build
    image: chapter-seed
