# .dev currently uses mailhog (but not postgres) hence the standalone service
version: "3.7"
services:
  mailhog:
    restart: unless-stopped
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
