name: Cypress Docker
on:
  push:
    branches-ignore:
      - 'renovate/**'
  pull_request:

jobs:
  cypress-run:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        browsers: [chrome, firefox]
        node-version: [16.x]
    steps:
      - name: Set Action Environment Variables
        run: |
          echo "CYPRESS_RECORD_KEY=${{ secrets.CYPRESS_RECORD_KEY }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Checkout Source Files
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set Chapter Environment Variables
        run: |
          cp .env.example .env

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          env: DOCKER_BUILDKIT=1
          record: ${{ env.CYPRESS_RECORD_KEY != 0 }}
          build: npm run build:docker-ci
          start: npm run start:docker
          wait-on: 'http://localhost:3000, http://localhost:5000/graphql'
          config: baseUrl=http://localhost:3000
          browser: ${{ matrix.browsers }}
