name: Migrate Database
on:
  workflow_dispatch:

jobs:
  migrate-db:
    runs-on: ubuntu-latest
    steps:
      - name: Migrate Via SSH
        uses: appleboy/ssh-action@4a03da89e5c43da56e502053be4bbcb293411883 # v0.1.6
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          passphrase: ${{ secrets.DIGITAL_OCEAN_SSH_PASSPHRASE }}
          port: 22
          script: |
            cd chapter
            docker compose down
            docker compose -f docker-compose.yml run app sh -c "npm run db:migrate"
            docker compose -f docker-compose.yml up --remove-orphans -d