name: Prepare to Deploy
on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Upload Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Use Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: '18.x'
      # Due to a quirk of Actions, the .env file overwrites the env: values you
      # set in the YAML. We create this empty file so that the build does not
      # fail, but pass the values in via env:
      - name: Create Dummy .env
        run: touch .env
      - name: Build Images
        env:
          NEXT_PUBLIC_SERVER_URL: ${{ secrets.CHAPTER_SERVER_URL }}
          NEXT_PUBLIC_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          NEXT_PUBLIC_AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          NEXT_PUBLIC_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          NEXT_PUBLIC_DEPLOYMENT_ENVIRONMENT: ${{ secrets.DEPLOYMENT_ENVIRONMENT }}
          NEXT_PUBLIC_CLIENT_URL: ${{ secrets.CHAPTER_CLIENT_URL }}
        run: |
          npm run build
          docker tag chapter-app chapter-app:$(git rev-parse --short HEAD)
          docker tag chapter-client chapter-client:$(git rev-parse --short HEAD)

      - name: Save Images
        run: |
          docker save -o app.tar chapter-app
          docker save -o client.tar chapter-client
      # TODO: upload to repository once this has been shown to work.
      - name: Upload Images
        uses: appleboy/scp-action@6d1fc191a822daa12faa45f3a985413f995ff5c5 # tag=v0.1.3
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          passphrase: ${{ secrets.DIGITAL_OCEAN_SSH_PASSPHRASE }}
          port: 22
          source: 'app.tar,client.tar'
          target: images
      - name: Upload Compose Files
        uses: appleboy/scp-action@6d1fc191a822daa12faa45f3a985413f995ff5c5 # tag=v0.1.3
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          passphrase: ${{ secrets.DIGITAL_OCEAN_SSH_PASSPHRASE }}
          port: 22
          source: 'docker-compose.yml,docker-compose.mailhog.yml'
          target: chapter
      - name: Unpack Images
        uses: appleboy/ssh-action@d91a1af6f57cd4478ceee14d7705601dafabaa19 # v0.1.7
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          passphrase: ${{ secrets.DIGITAL_OCEAN_SSH_PASSPHRASE }}
          port: 22
          script: |
            docker image prune -f
            docker load -i images/app.tar
            docker load -i images/client.tar