name: Reset Dev Database
on:
  workflow_dispatch:

jobs:
  reset-dev-db:
    name: Reset Dev Database
    runs-on: ubuntu-latest
    steps:
      - name: Reset Via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          passphrase: ${{ secrets.DIGITAL_OCEAN_SSH_PASSPHRASE }}
          port: 22
          script: docker compose -f docker-compose.seed.yml run seed npm run db:reset
